### ISSUE TITLE
"Oops, something went wrong" error when using MenuComplete function

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11279]
### Windows Terminal version (or Windows build number)

1.11.2421.0

### Steps to reproduce

1. open a "Windows Powershell" tab
2. type a cmdlet (i.e. get-netadapter used in this case) followed by space
3. type Ctrl+Space to invoke completion function

### Expected Behavior

From function's description:

`Complete the input if there is a single completion, otherwise complete the input by selecting from a menu of possible completions.`

### Actual Behavior

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 16 Keys:
 g e t - n e t a d a p t e r Space Ctrl+Space

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -28.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

- the bug was filed here because Ctrl+Space works as expected in a standalone PowerShell session. 
- if there is no space after the command MenuCompletion works in WT
- if after space a dash is entered the MenuCompletion works in WT

**Comment by DHowett** [comment]
This is unfortunately a PSReadline issue! It will also happen in a standard console window where the buffer height is set to be the same as the window height -- indicating that they don't handle this state correctly.

**Comment by DHowett** [comment]
(The "top" being a negative number suggests that they're doing math based on the buffer height, and they are not making sure that the region fits on screen.)

This may have been fixed as of a newer version of PSReadline!
