### ISSUE TITLE
Suddenly unable to launch PowerShell in Windows Terminal via Run/shell

### ISSUE THREAD

**Issue by ninbura** [microsoft/terminal#16660]
### Windows Terminal version

1.19.10292.0

### Windows build number

10.0.22631.0

### Other Software

PowerShell 7 - v7.4.1
PowerShell - v5.1.22621.2506

#### via run
1. open Run
2. input `wt pwsh`
3. click "OK"

#### via shell
1. open PowerShell, PowerShell 7, or Command Prompt
2. input `wt pwsh` or `wt PowerShell`

#### nuance
For whatever reason I've found that it is sometimes necessary to run `wt [shell]` more than once before Windows Terminal will even launch to print the error message. Almost as if Terminal itself is hard crashing before it can display.

### Expected Behavior

1. `wt pwsh` launches Windows Terminal with the PowerShell 7 profile without error. 
2. `wt PowerShell` launches Windows Terminal with the PowerShell profile without error.

### Actual Behavior

1. `wt pwsh` launches Windows Terminal with the PowerShell 7 profile and displays the following error & exit code:
    - ```PowerShell
      Process terminated. The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.
         at System.Environment.FailFast(System.String, System.Exception)
         at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
         at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
      System.TypeInitializationException: The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.
      ---> System.ComponentModel.Win32Exception (126): The specified module could not be found.
         at System.Management.Automation.Internal.SecuritySupport.GetSaferPolicy(String path, SafeHandle handle)
         at System.Management.Automation.Security.SystemPolicy.TestSaferPolicy(String testPathScript, String testPathModule)
         at System.Management.Automation.Security.SystemPolicy.GetAppLockerPolicy(String path, SafeHandle handle)
         at System.Management.Automation.Security.SystemPolicy.GetLockdownPolicy(String path, SafeHandle handle)
         at System.Management.Automation.Security.SystemPolicy.GetSystemLockdownPolicy()
         at System.Management.Automation.Runspaces.InitialSessionState..cctor()
         --- End of inner exception stack trace ---
         at System.Management.Automation.Runspaces.InitialSessionState.CreateDefault2()
         at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
      [process exited with code 2148734499 (0x80131623)]
      You can now close this terminal with Ctrl+D, or press Enter to restart.
      ```
2. `wt PowerShell` launches Windows Terminal with the PowerShell profile and displays the following error & exit code:
   - ```PowerShell
     Internal Windows PowerShell error.  Loading managed Windows PowerShell failed with error 8009001d.

     [process exited with code 4294901760 (0xffff0000)]
     You can now close this terminal with Ctrl+D, or press Enter to restart.
     ```

**Comment by ninbura** [comment]
# more details
From what I can tell, this started to occur after updating Windows Terminal to version `1.19.10292.0`. The issue is replicable on 3 systems that I own, all on different chipsets, but running the same Windows Edition, Version, & OS Build.
1. Windows Edition - `Windows 11 Pro N for Workstations`
2. Windows Version - `23H2`
3. Windows OS Build - `22631.3085`

There is another issue on the [PowerShell repository](https://github.com/PowerShell/PowerShell) (https://github.com/PowerShell/PowerShell/issues/20595) that mentions this same error, but it has been closed as in was mentioned to be an issue with Windows terminal; linking to this https://github.com/microsoft/terminal/issues/16051. Which has been locked due to participant's "spicy" behavior. However, I'm not sure I have the same issue as running the [Get-EnvsWithEmbeddedNull script](https://gist.github.com/lhecker/393252fb1e95b3bc118d40ace802a505) mentioned in https://github.com/microsoft/terminal/issues/16051 does not list any corrupt registry entries on any of my 3 systems.

# things I've tried
1. restarting my systems
2. checking for updates
3. un-installing & re-installing Windows Terminal via winget
4. Running the [Get-EnvsWithEmbeddedNull script](https://gist.github.com/lhecker/393252fb1e95b3bc118d40ace802a505) script, as mentioned before.
5. manually searching registry locations in regedit

**Comment by PiTomar** [comment]
I guess this is a bug in the v1.19 Release and is will be probably fixed in v1.20. See:
https://github.com/microsoft/terminal/releases/tag/v1.20.10303.0

**Comment by mjpraxis** [comment]
@PiTomar I have tried the preview version 1.20.240130003-preview

I have still have the exact same issues as @ninbura 

And has also tried the script that finds null values in environment values in registry.

**Comment by zadjii-msft** [comment]
Yea pretty sure this is /dup #16623, which is already fixed in [v1.19.10302.0](https://github.com/microsoft/terminal/releases/tag/v1.19.10302.0)

**Comment by aaronedev** [comment]
it starts happening for me as well with latest [v1.22.3232.0]

**Comment by DHowett** [comment]
@aaronedev please file a new bug, fill out the template, and include a screenshot.
