### ISSUE TITLE
Error trying to use double quotes with git commit -m

### ISSUE THREAD

**Issue by programmingwithalex** [microsoft/terminal#17230]
### Windows Terminal version

1.19.11213.0

### Windows build number

10.0.19043.2364

### Steps to reproduce

Run the following commands:

```
git add *
git commit -m "
```

Issue happens immediately after typing the `"` on the second line.

### Expected Behavior

able to use double quotes with `git commit -m "message"`

currently only able to use single quotes

### Actual Behavior

```
Last 71 Keys:
 c d Space A b Tab a l Backspace Backspace Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Delete Delete c d Space a b Tab Tab Tab Tab Shift+Tab d e Tab f Tab Enter
 g i t Space s t a t u s Enter
 g i t Space a d d Space * Enter
 g i t Space c o m m i t Space - m Space "

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by zadjii-msft** [comment]
This looks like a PSReadline bug, specifically https://github.com/PowerShell/PSReadLine/issues/1306. What version of PsReadline are you using/? Does the latest version fix this?
