### ISSUE TITLE
Error when pasting code

### ISSUE THREAD

**Issue by Ma3yTa** [microsoft/terminal#4524]
# Environment

```none
Windows build number: 
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19559.0 Microsoft Windows NT 10.0.19559.0
Windows Terminal version : 0.8.10261.0
```

# Steps to reproduce

1. open windows terminal -> powershell session
2. copy and paste code into wt
```powershell
$hotkeysFile = "$home\hotkeys.ahk"
$keys = @"
#SingleInstance, Force
; https://www.autohotkey.com/docs/Hotkeys.htm
; # win ! alt ^ control + shift 
^!t:: run wt, return
#+p:: run powershell, return
#n:: run notepad++, return
#c:: run code, return
#v:: run devenv, return
#f:: run firefox, return
#e:: run fman, return
#t:: run wt, return
#a:: run "sudo" "wt.exe", return
Space:: send {Space down}
	sleep 0.001 
	send {Space up}
	return
Space & t:: run wt, return
#b::
{ SendMode Input
  Run, ms-settings:bluetooth
  WinWaitActive, Settings
  Sleep 300
  Send,{Tab}{Space}
  WinClose, A
  return
}
; AutoHotkey Media Keys
^Down:: 
	Send {Media_Play_Pause}
	return
^Left:: 
	Send {Media_Prev}
	return
^Right:: 
	Send {Media_Next}
	return
^NumpadMult:: 
	Send {Volume_Mute}
	return
^NumpadAdd:: 
	Send {Volume_Up}
	return
^NumpadSub:: 
	Send {Volume_Down}
	return
^!p::Pause ; Pause script with Ctrl+Alt+P
^!s::Suspend ; Suspend script with Ctrl+Alt+S
^!r::Reload ; Reload script with Ctrl+Alt+R
^!q::ExitApp ; Exit script with Ctrl+Alt+Q
"@
```
![image](https://user-images.githubusercontent.com/660379/74198937-54840e00-4c95-11ea-9d96-65605e8aa2a2.png)
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 Space { V o l u m e _ D o w n } Enter
 Tab r e t u r n Enter
 ^ ! p : : P a u s e Space ; Space P a u s e Space s c r i p t Space w i t h Space C t r l + A l t + P Enter
 ^ ! s : : S u s p e n d Space ; Space S u s p e n d Space s c r i p t Space w i t h Space C t r l + A l t + S Enter
 ^ ! r : : R e l o a d Space ; Space R e l o a d Space s c r i p t Space w i t h Space C t r l + A l t + R Enter
 ^ ! q : : E x i t A p p Space ; Space E x i t Space s c r i p t Space w i t h Space C t r l + A l t + Q Enter
 " @

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -6.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```
# Expected behavior
All should work fine like in regular Powershell terminal.

# Actual behavior
Error in the console **Oops, something went wrong**

**Comment by DHowett-MSFT** [comment]
Okay, can you provide _more info about the error_? Does it crash? Does it print a bunch of red text? Does it tell you to _file a bug on PSReadline_?

**Comment by Ma3yTa** [comment]
![image](https://user-images.githubusercontent.com/660379/74199002-8006f880-4c95-11ea-988f-43466076e4c3.png)

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 Space { V o l u m e _ D o w n } Enter
 Tab r e t u r n Enter
 ^ ! p : : P a u s e Space ; Space P a u s e Space s c r i p t Space w i t h Space C t r l + A l t + P Enter
 ^ ! s : : S u s p e n d Space ; Space S u s p e n d Space s c r i p t Space w i t h Space C t r l + A l t + S Enter
 ^ ! r : : R e l o a d Space ; Space R e l o a d Space s c r i p t Space w i t h Space C t r l + A l t + R Enter
 ^ ! q : : E x i t A p p Space ; Space E x i t Space s c r i p t Space w i t h Space C t r l + A l t + Q Enter
 " @

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -6.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by DHowett-MSFT** [comment]
I see you edited your issue. This bug needs to be filed on [PSReadline](https://github.com/powershell/psreadline). Thanks!

**Comment by Ma3yTa** [comment]
in regular powershell all works fine

**Comment by DHowett-MSFT** [comment]
Yes. The bug is that PSReadline is trying to change the contents off the top of the screen, but Terminal _doesn't have any_. PSReadline cannot handle the screen buffer size being the same as the viewport size.
