### ISSUE TITLE
ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by HppZ** [microsoft/terminal#9315]
# Environment

```none
Windows build number: 19042.804
Windows Terminal version (if applicable): 1.5.10411.0

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -53.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

just:
ctrl+v copy a lot of string into ws, and press ESC.

**Comment by zadjii-msft** [comment]
I'm presuming you're using powershell. What version? Are you using the PSReadline module? If so, which version? 

There's [a bunch of similar issues](https://github.com/microsoft/terminal/issues?q=is%3Aissue+ArgumentOutOfRangeException+is%3Aclosed) - did you try searching those?

**Comment by HppZ** [comment]
powershell 7.1.2.
don't know if i am using PSReadline module.

**Comment by zadjii-msft** [comment]
By any chance, is this any of:
* PowerShell autocomplete crashes if larger than current screen #7136
* Strange error if command is larger than screen #7192
* Error when pasting code #4524

All of those look like they have the same error message
