### ISSUE TITLE
Unicode Emoji Causes Exception

### ISSUE THREAD

**Issue by IdioticProphet** [microsoft/terminal#9672]
PSReadLine: 2.0.0
PowerShell: 5.1.21296.1000
OS: Microsoft Windows 10.0.21296

Expected Behavior: Not an exception, does command as usual

Actual Behavior: Causes an exception and prevents any command containing unicode emoji from working, but not every unicode emoji, haven't been able to test which emojis extensively, I have noticed that if they paste and display properly, they do not tend to cause errors, I imagine the traceback is more useful.

```

### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \uD83D at index 0 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

PS W:\desktop\tiktokdl> �✌✌
Symbols typed in above example, using windows emoji keyboard: 👍✌✌

**Comment by skyline75489** [comment]
This is not a terminal issue, to be exact. I think you should file this at https://github.com/PowerShell/PSReadLine/issues

btw can you try PowerShell Core? I think Windows PowerShell (aka PowerShell 5) is not being actively maintained now.

**Comment by IdioticProphet** [comment]
> This is not a terminal issue, to be exact. I think you should file this at https://github.com/PowerShell/PSReadLine/issues
> 
> btw can you try PowerShell Core? I think Windows PowerShell (aka PowerShell 5) is not being actively maintained now.

Yes, typing these emojis into powershell shows the question marks, but doesnt really *care* or throw an exception. I believe the issue has to do with how terminal renders/passes unicode, not super sure.

**Comment by IdioticProphet** [comment]
Ah wait. turns out I'm stupid
> Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
